import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <main className="max-w-7xl mx-auto px-4">
          <div className="p-6">
            <Link href="/">
              <h2 className="text-2xl text-bold">Pokemon</h2>
            </Link>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
